# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    git config --global user.email "ambikagarg1101@gmail.com"
    git config --global user.name "ambika-garg"
    git checkout -b prod
    git add .
    git commit -m "push into prod branch"
    git push --set-upstream origin prod
  displayName: 'Run a multi-line script'
