name: Test DAGs

on:
  push: 
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          max-line-length: 120

  tests:
    runs-on: ubuntu-latest
    needs: [flake8]
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt