name: Test DAGs

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  # Runs the code validation tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     
  # goodbye:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: goodbye world
  #       run: echo "Good Bye!"
  #       shell: bash

