name: Test DAGs

on:
  pull_request: 
    branches:
      - 'main'
  push: 
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          max-line-length: 120

  tests:
    runs-on: ubuntu-latest
    needs: [flake8]
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pytest
        run: pytest tests/
        # After the PR is raised, post notification to review to go ahead and review

  deploy:
    runs-on: ubuntu-latest
    needs: [flake8, tests]
    steps:
      - name: Deploy to Prod IR
      - run: |
          git checkout -b prod
          git add .
          git commit -m "Updated"
          git push

      - name: Switch back to main branch
        run: |
          git checkout main